name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Build recursively
        run: docker-compose -f .misc/docker/test/recursive/build.yml build
      - name: Test
        run: docker-compose -f .misc/docker/test/docker-compose.yml run --rm asis
